services:
  app:
    image: ghcr.io/discordanalytics/website
    ports:
      - '80:80'
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    # Uncomment if you need to customize the website configuration (not required)
    #    volumes:
    #      - ./config.js:/app/dist/public/config.js:ro
    restart: unless-stopped

  db:
    image: mongo:8
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: mongosh --username root --password example --authenticationDatabase admin --eval "db.adminCommand('ping')" localhost:27017/admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  api:
    image: ghcr.io/discordanalytics/api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/heatlh']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped

volumes:
  mongo_data: