services:
  app:
    image: ghcr.io/discordanalytics/website@sha256:70807593fee054f131b7a4c91f5e27dd0209035613447907994eecd8703bbab3
    ports:
      - '80:80'
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    # Uncomment if you need to customize the website configuration (not required)
    #    volumes:
    #      - ./config.js:/app/dist/public/config.js:ro
    restart: unless-stopped

  db:
    image: mongo:8@sha256:7abfba0d07c9330373f8173981ea4d09cd8a82cdf0e86ccaf7008848d1d24f62
    volumes:
      - discord-analytics-database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: mongosh --username root --password example --authenticationDatabase admin --eval "db.adminCommand('ping')" localhost:27017/admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  api:
    image: ghcr.io/discordanalytics/api@sha256:05de86f029a2e91c1d466846ebd83159b55f1974844611c063ea49c4d64dd5f5
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/heatlh']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped
