services:
  app:
    image: ghcr.io/discordanalytics/website@sha256:c7d83b081c4cb3e8c4b983e2c23d989e56d3e61c2e55d645623381d43f621ae8
    ports:
      - '80:80'
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    # Uncomment if you need to customize the website configuration (not required)
    #    volumes:
    #      - ./config.js:/app/dist/public/config.js:ro
    restart: unless-stopped

  db:
    image: mongo:8@sha256:7abfba0d07c9330373f8173981ea4d09cd8a82cdf0e86ccaf7008848d1d24f62
    volumes:
      - discord-analytics-database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: mongosh --username root --password example --authenticationDatabase admin --eval "db.adminCommand('ping')" localhost:27017/admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  api:
    image: ghcr.io/discordanalytics/api@sha256:56484c8064a3887ed764e0e1a21355fab6c04253cde6650841601c12675e0be9
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/heatlh']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped
