worker_processes auto;

events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;
  sendfile on;
  keepalive_timeout 65;

  access_log /var/log/nginx/access.log;
  error_log /var/log/nginx/error.log;

  server {
    listen 80;
    root /usr/share/nginx/html;

    location /api/ {
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass http://api:3001/;
    }

    location /docs/ {
      proxy_set_header Host discordanalytics.xyz;
      proxy_ssl_server_name on;

      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      proxy_pass https://discordanalytics.xyz;
    }

    location = / {
      return 301 /dash;
    }

    if ($request_uri ~ ^/(.*)\.html$) {
      return 301 /$1;
    }

    location / {
      try_files $uri $uri/ $uri.html $uri/index.html /index.html;
      index index.html;
    }
  }
}