name: CI

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        linter:
          - name: oxlint
            command: 'pnpm oxlint .'
          - name: eslint
            command: 'pnpm eslint .'

    name: Lint - ${{ matrix.linter.name }}
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.linter.name }}
        run: ${{ matrix.linter.command }}

  locales:
    runs-on: ubuntu-latest

    name: Check for missing locale keys
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Run check
        run: pnpm locales:check

  build:
    runs-on: ubuntu-latest
    name: Build TypeScript
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
